### ISSUE TITLE
Add support for Video Recording

### ISSUE THREAD

**Issue by britzl** [defold/extension-gpgs#20]
https://developers.google.com/games/services/android/videoRecording

**Comment by ekharkunov** [comment]
After update sdk to v2 #47 current task doesn't make sense because of
https://developers.google.com/games/services/android/videoRecording
<img width="944" alt="Screenshot 2024-02-09 at 10 41 35" src="https://github.com/defold/extension-gpgs/assets/770105/de648e47-0de8-4c53-98e3-5a2bf2389790">

**Comment by AGulev** [comment]
thx
