### ISSUE TITLE
gpgs.leaderboard_submit_score() submits incorrect score to the leaderboard

### ISSUE THREAD

**Issue by jm1175** [defold/extension-gpgs#25]
Whenever I submit a score to my game's leaderboard the score shown on the leaderboard ends up being a long negative number instead of the actual score.

For example:

gpgs.leaderboard_submit_score(leaderboard_id, 5)

Instead of the leaderboard showing "5" as the score, it shows "-7,017,514,852,6...".

I've noticed if I call gpgs.leaderboard_get_player_score() right before submitting the score the leaderboard will show the correct score as "5".

There's also a problem with gpgs.leaderboard_get_player_score() though, because it crashes the game if the player doesn't already have a score on the leaderboard. The crash shows the following error:

Attempt to invoke interface method 'java.lang.String com.google.android.gms.games.leaderboard.LeaderboardScore.getDisplayRank()' on a null object reference

**Comment by britzl** [comment]
> There's also a problem with gpgs.leaderboard_get_player_score() though, because it crashes the game if the player doesn't already have a score on the leaderboard 

Created new issue here:

https://github.com/defold/extension-gpgs/issues/26

**Comment by britzl** [comment]
I'm not able to reproduce the first part with the incorrect score. Can you provide additional details so that I can reproduce it.

What kind of Leaderboard is it? Does the player already have a score on the leaderboard? What other gpgs functions have you called before your call to leaderboard_submit_score()?

**Comment by jm1175** [comment]
The leaderboard settings in the Google Play Console are the following:

- Number format
- 0 decimals
- No custom units
- Sort order is largest first
- Tamper protection on
- No score limits set

This happens on the first submission when the player doesn't have a score on the leaderboard, but even when they do have a score any new submissions will continue to show up like "-7,017,514,852,600" (or something similar). They aren't always negative numbers but always 13 digits as far as I can tell.

The only other gpgs functions called before gpgs.leaderboard_submit_score() are the following:
gpgs.set_callback()
gpgs.silent_login()
gpgs.is_logged_in()

**Comment by britzl** [comment]
I'm unable to reproduce the problem. This is the snippet of code I'm using:

```
	gpgs.set_callback(function(self, message_id, message)
		print(message_id)
		pprint(message)
		if message_id == gpgs.MSG_SIGN_IN or message_id == gpgs.MSG_SILENT_SIGN_IN then
			print("is logged in", gpgs.is_logged_in())
			if message.status == gpgs.STATUS_SUCCESS then
				gpgs.leaderboard_submit_score("CgkIq5-gxcsVEAIQBg", 51)
				gpgs.leaderboard_get_player_centered_scores("CgkIq5-gxcsVEAIQBg", gpgs.TIME_SPAN_ALL_TIME, gpgs.COLLECTION_PUBLIC, 10)
				gpgs.leaderboard_show("CgkIq5-gxcsVEAIQBg", gpgs.TIME_SPAN_ALL_TIME, gpgs.COLLECTION_PUBLIC)
			end
		elseif message_id == gpgs.MSG_GET_PLAYER_CENTERED_SCORES then
			local s = ""
			for _,score in ipairs(message) do
				score = json.decode(score)
				s = s .. ("%s - %s (%s)\n"):format(score.score_holder_name, score.display_score, score.display_rank)
			end
			print(s)
		end
	end)

	gpgs.silent_login()
```

The log shows:

```
                         I  INFO:GpgsExt: GpgsLeaderboard_SubmitScore CgkIq5-gxcsVEAIQBg score: 51.000000
                         D  DEBUG:SCRIPT: 9
                         D  DEBUG:SCRIPT:
                         D  { --[[0x7017f37290]]
                         D    1 = "{"display_rank":"1st","display_score":"51","rank":1,"score":51,"timestamp":1600005190
                            248,"score_holder_name":"Britzl","score_holder_icon":"content:\/\/com.google.android.gms.gam
                            es.background\/images\/9201f1f5\/4461","score_holder_image":"content:\/\/com.google.android.
                            gms.games.background\/images\/9201f1f5\/4462"}"
                         D  }
```

And the on-screen leaderboard from the call to gpgs.leaderboard_show() also shows the correct score. Which leaderboard function do you use when you see the score show up as an incorrect value?

**Comment by jm1175** [comment]
I use gpgs.leaderboard_show() but i also tried gpgs.leaderboard_list() and they both still show the incorrect score.

I tried creating a brand new bare-bones defold project and copied your gpgs code above into the project. Unfortunately I still got the same issue with the incorrect score.

Here's what the gpgs.script looks like:

```
function init(self)
	if gpgs then
		gpgs.set_callback(function(self, message_id, message)
			print(message_id)
			pprint(message)
			if message_id == gpgs.MSG_SIGN_IN or message_id == gpgs.MSG_SILENT_SIGN_IN then
				print("is logged in", gpgs.is_logged_in())
				if message.status == gpgs.STATUS_SUCCESS then
					gpgs.leaderboard_submit_score("CgkIpYykgvcEEAIQAA", 51)
					gpgs.leaderboard_get_player_centered_scores("CgkIpYykgvcEEAIQAA", gpgs.TIME_SPAN_ALL_TIME, gpgs.COLLECTION_PUBLIC, 10)
					gpgs.leaderboard_show("CgkIpYykgvcEEAIQAA", gpgs.TIME_SPAN_ALL_TIME, gpgs.COLLECTION_PUBLIC)
				end
			elseif message_id == gpgs.MSG_GET_PLAYER_CENTERED_SCORES then
				local s = ""
				for _,score in ipairs(message) do
					score = json.decode(score)
					s = s .. ("%s - %s (%s)\n"):format(score.score_holder_name, score.display_score, score.display_rank)
				end
				print(s)
			end
		end)
		gpgs.silent_login()
	end
end
```

And here is what the log shows:

```
DEBUG:SCRIPT: 9
DEBUG:SCRIPT: 
{ --[[0x9f2c6380]]
  1 = "{"display_rank":"1st","display_score":"-5,550,594,473,815,179,300","rank":1,"score":-5550594473815179213,"timestamp":1600083593095,"score_holder_name":"DiplomaticLever1","score_holder_icon":"content:\/\/com.google.android.gms.games.background\/images\/61664160\/82","score_holder_image":"content:\/\/com.google.android.gms.games.background\/images\/61664160\/83"}"
}
DEBUG:SCRIPT: DiplomaticLever1 - -5,550,594,473,815,179,300 (1st)
```

I also had a problem while testing where it wouldn't log in anymore. I checked the logs and found this error message:

```
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: ****
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: **** APP ID IS NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: **** Application ID ( 169387558437) must be a numeric value.
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: **** Please verify that your manifest refers to the correct project ID.
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: ****
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: **** For more information, refer to the troubleshooting guide:
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: **** https://developers.google.com/games/services/android/troubleshooting#check_your_metadata_tags
09-14 18:46:33.040  3017 18039 E PlayGamesServices[ValidateServiceOp]: ****

```

I got it to log in again after reading about the same issue [here](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2013) and editing this line in the gpgs AndroidManifest:
```
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u003{{gpgs.app_id}}" />
```

**Comment by britzl** [comment]
Thanks @jm1175 ! I'm still unsure what's going on, but I'm guessing it's an issue with double vs long number presentation. The score is read from Lua as a lua_Number which is a double. It is then passed on to Java and the `LeaderboardsClient. submitScore()` which expects a long. And I'm suspecting that it goes wrong somewhere in the chain of calls.

Which device are you testing on btw?

**Comment by jm1175** [comment]
I'm testing on an Alcatel u5 running Android 6.0. It's the only Android device I have right now otherwise I would have tested on something else. Could the problem I'm having with gpgs not reporting the correct score be an isolated issue on these older devices / Android versions?

**Comment by britzl** [comment]
> I'm testing on an Alcatel u5 running Android 6.0

I thought maybe it had to do with the device using a 32bit CPU, but that one is 64bit. (and it should not matter)

Could you please try using this version:

https://github.com/defold/extension-gpgs/archive/Issue-25-submit-score-bug.zip

And share the logcat output. We're looking for the following two lines of logging:

```
                         I  INFO:GpgsExt: GpgsLeaderboard_SubmitScore CgkIq5-gxcsVEAIQBg score: 51.000000
                GpgsJNI  D  GpgsJNI.submitScore() 51
```

The first line with `GpgsLeaderboard_SubmitScore` is the score as it is read from Lua to C.

The second line `GpgsJNI.submitScore` is how it is received on the Java side and sent to the LeaderboardsClient.

I added an explicit cast from double to long before sending it to Java and I'm hoping that they match up on the C and Java side.

**Comment by jm1175** [comment]
They didn't match unfortunately, here's the logcat output:

```
09-15 17:37:52.806 11272 11287 D defold  : DEBUG:SCRIPT: 2
09-15 17:37:52.806 11272 11287 D defold  : DEBUG:SCRIPT: 
09-15 17:37:52.806 11272 11287 D defold  : { --[[0x9efe7090]]
09-15 17:37:52.806 11272 11287 D defold  :   status = 1
09-15 17:37:52.806 11272 11287 D defold  : }
09-15 17:37:52.808 11272 11287 D defold  : DEBUG:SCRIPT: is logged in	true
```
```
09-15 17:37:52.808 11272 11287 I defold  : INFO:GpgsExt: GpgsLeaderboard_SubmitScore CgkIpYykgvcEEAIQAA score: 51.000000
09-15 17:37:52.810 11272 11287 D GpgsJNI : GpgsJNI.submitScore() -5446048218141949901
```
```
09-15 17:38:36.263 11272 11287 D defold  : DEBUG:SCRIPT: 9
09-15 17:38:36.264 11272 11287 D defold  : DEBUG:SCRIPT: 
09-15 17:38:36.264 11272 11287 D defold  : { --[[0x9efea490]]
09-15 17:38:36.264 11272 11287 D defold  :   1 = "{"display_rank":"1st","display_score":"-5,446,048,218,141,950,000","rank":1,"score":-5446048218141949901,"timestamp":1600160568360,"score_holder_name":"DiplomaticLever1","score_holder_icon":"content:\/\/com.google.android.gms.games.background\/images\/61664160\/82","score_holder_image":"content:\/\/com.google.android.gms.games.background\/images\/61664160\/83"}"
09-15 17:38:36.264 11272 11287 D defold  : }
09-15 17:38:36.264 11272 11287 D defold  : DEBUG:SCRIPT: DiplomaticLever1 - -5,446,048,218,141,950,000 (1st)
09-15 17:38:36.264 11272 11287 D defold  : 
```

**Comment by britzl** [comment]
@jm1175 I've pushed a new commit to the branch. Would you mind updating and testing again?

**Comment by jm1175** [comment]
@britzl The scores matched up this time! The old score on the leaderboard was updated and now shows the correct score.

```
09-16 10:00:38.366 29630 29645 I defold  : INFO:GpgsExt: GpgsLeaderboard_SubmitScore CgkIpYykgvcEEAIQAA score: 51.000000
09-16 10:00:38.385 29630 29645 D GpgsJNI : GpgsJNI.submitScore() 51.0
```

**Comment by britzl** [comment]
Excellent! Thanks for helping out with testing. I'm merging this to master and making a new release.
