### ISSUE TITLE
Cloud save data crash

### ISSUE THREAD

**Issue by grononmc** [defold/extension-gpgs#37]
When i try use gpgs.snapshot_commit_and_close(), the just crashs.

Galaxy A01 Core, Android 10
Defold version: 1.2.183
GPGS 2.3.0

[_crash.txt](https://github.com/defold/extension-gpgs/files/6733509/_crash.txt)

```
# 1 pc      0x362b2 ...droid.runtime/lib/bionic/libc.so abort+161
# 2 pc     0x2a7809 ...om.android.runtime/lib/libart.so _ZN3art7Runtime5AbortEPKc+1676
# 3 pc       0x255f /system/lib/libbase.so _ZN7android4base10LogMessageD2Ev+406
# 4 pc     0x1b8a27 ...om.android.runtime/lib/libart.so _ZN3art9JavaVMExt8JniAbortEPKcS2_+1194
# 5 pc     0x1b8bc9 ...om.android.runtime/lib/libart.so _ZN3art9JavaVMExt9JniAbortFEPKcS2_z+64
# 6 pc     0x2dcc8b ...om.android.runtime/lib/libart.so _ZNK3art6Thread13DecodeJObjectEP8_jobject+486
# 7 pc     0x1adae1 ...om.android.runtime/lib/libart.so _ZN3art12_GLOBAL__N_111ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS1_12InstanceKindEP8_jobjectb+80
# 8 pc     0x1ad009 ...om.android.runtime/lib/libart.so _ZN3art12_GLOBAL__N_111ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS0_12JniValueTypeE+424
# 9 pc     0x1ad15b ...om.android.runtime/lib/libart.so _ZN3art12_GLOBAL__N_111ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS0_12JniValueTypeE+762
#10 pc     0x1ac853 ...om.android.runtime/lib/libart.so _ZN3art12_GLOBAL__N_111ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS0_12JniValueTypeE+634
#11 pc     0x1b0741 ...om.android.runtime/lib/libart.so _ZN3art12_GLOBAL__N_18CheckJNI13CheckCallArgsERNS_18ScopedObjectAccessERNS0_11ScopedCheckEP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDNS_10InvokeTypeEPKNS0_7VarArgsE+100
#12 pc     0x1afabb ...om.android.runtime/lib/libart.so _ZN3art12_GLOBAL__N_18CheckJNI11CallMethodVEPKcP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDSt9__va_listNS_9Primitive4TypeENS_10InvokeTypeE+542
#13 pc     0x1a1c11 ...om.android.runtime/lib/libart.so _ZN3art12_GLOBAL__N_18CheckJNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+44
#14 pc      0x2e498 ...sKw==/lib/arm/libCircleWiggle.so _ZN7_JNIEnv14CallVoidMethodEP8_jobjectP10_jmethodIDz+32
#15 pc      0x2cf3c ...sKw==/lib/arm/libCircleWiggle.so _ZL31GpgsDisk_SnapshotCommitAndCloseP9lua_State+756
```

**Comment by britzl** [comment]
Could you please share the snippet of code where you are calling `gpgs.snapshot_commit_and_close()`?

**Comment by grononmc** [comment]
```
local bt_save_data = gui.get_node("bt_save_data")
if(gui.pick_node(bt_save_data, action.x, action.y)) then
    if(gpgs) then
        local success, err = gpgs.snapshot_set_data("ThisIsMyData")
        if(success) then
            gpgs.snapshot_commit_and_close()
        else
            print("fail save", err)
        end
    end	
end
```

**Comment by britzl** [comment]
Thanks. I don't see anything obivous. Do you @AGulev? I think we'll have to investigate this and try it ourselves.

**Comment by AGulev** [comment]
I'll try to reproduce it.

**Comment by AGulev** [comment]
I can't reproduce this issue using the same piece of code:
```
    dirtylarry:button("save_snapshot", action_id, action, function ()
        if gpgs then
            local png, w, h = screenshot.png()
            local success, err = gpgs.snapshot_set_data("ThisIsMyData")
            if(success) then
                gpgs.snapshot_commit_and_close()
            else
                print("fail save", err)
            end
        end
    end)
  ```


Is this log from logical? it looks strange on my machine? could you please try one more time and send me a full log
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/2209596/124510275-bfc30880-ddd3-11eb-8d22-2822bbc65806.png">

**Comment by grononmc** [comment]
Of course, i made this .zip.

This file _crash, i get from device using the command: "adb shell "run-as com.sixsteelgames.circlewiggle sh -c 'cat /data/data/com.sixsteelgames.circlewiggle/files/_crash'" > c:/_crash"

[_crash.zip](https://github.com/defold/extension-gpgs/files/6766124/_crash.zip)

**Comment by AGulev** [comment]
Thank you, but I mean 

> adb logcat 

and then reproduce the issue again. 

Logs will have a bit more info what's going on right before crash.

**Comment by grononmc** [comment]
[logcat.txt](https://github.com/defold/extension-gpgs/files/6766450/logcat.txt)

**Comment by AGulev** [comment]
It's hard to understand what's going on when i can't repo it.

Could you please try if you have crash using 
```
gpgs.snapshot_commit_and_close({
    description = "text",
})
```
and also  (with screenshots lib https://github.com/britzl/defold-screenshot/archive/master.zip )
```
local png, w, h = screenshot.png()
gpgs.snapshot_commit_and_close({
    description = "text",
    coverImage = png
})
```

**Comment by grononmc** [comment]
Yes, both options make a crash.

[logcat1.txt](https://github.com/defold/extension-gpgs/files/6791786/logcat1.txt)
[logcat2.txt](https://github.com/defold/extension-gpgs/files/6791785/logcat2.txt)

**Comment by britzl** [comment]
Does other gpgs functions work?

**Comment by AGulev** [comment]
Also it would be useful to check example  (but using your package name and key)

Do you have another phone to check it there? if not could you share `apk` with me to check if I can reproduce it using your `apk`.

**Comment by AGulev** [comment]
@grononmc  I found the reason of the issue and was able to reproduce it on my phone (when build armv7 architecture only)
The PR is on review and will be merged soon, but now you can check this fix using the following branch:
https://github.com/defold/extension-gpgs/archive/refs/heads/issue-37-fix-jlong.zip
(just use this ref. instead of ref. to master branch)

**Comment by grononmc** [comment]
Wow, works perfect, thank you so much.
