### ISSUE TITLE
GPGS Example does not log in. Tested on Android emulator and actual Samsung device

### ISSUE THREAD

**Issue by dkyles77788** [defold/extension-gpgs#50]
Pressed the Login button and got the login false message. Tested on emulator and on actual Samsung device.
Used Extension GPGS Master and Extension GPGS 3.0.2

<img width="981" alt="Testing gpgsexample" src="https://github.com/defold/extension-gpgs/assets/7681778/9525c85d-4bce-4d06-888e-708999e65357">

**Comment by dkyles77788** [comment]
I have some error logs from the example if that helps at all...from my Samsung Note 10:

com.defold.extension.gpgs/com.google.android.gms.auth.api.signin.internal.SignInHubActivity} to Window{d8c938f u0 com.defold.extension.gpgs/com.dynamo.android.DefoldActivity} displayId=0 

com.defold.extension.gpgs/com.google.android.gms.auth.api.signin.internal.SignInHubActivity t45}#0
04-30 22:10:54.652  1000  1131  2159 D MdnieScenarioControlService:  packageName : com.defold.extension.gpgs    className : com.dynamo.android.DefoldActivity

04-30 22:10:56.830  1000  1131  7181 D SGM:GameManager: identifyGamePackage. com.defold.extension.gpgs, mCurrentUserId: 0, callerUserId: 0, callingMethodInfo: com.android.server.ssrm.SortingMachine.isGame(SortingMachine.java:162)
04-30 22:10:56.830  1000  1131  7181 D SGM:PkgDataHelper: getGamePkgData(). com.defold.extension.gpgs
04-30 22:10:56.832  1000  1131  1818 D InputReader: Btn_touch(6): value=1 when=218356.904376
04-30 22:10:56.832  1000  1131  1818 I InputReader: Touch event's action is 0x0 (id=6, t=0) [pCnt=1, s=0.22942 ] when=218356.904376
04-30 22:10:56.833  1000  1131  1817 I InputDispatcher: Delivering touch to (2093): action: 0x4, f=0x0, d=0, '1469381', t=1 
04-30 22:10:56.833  1000  1131  1817 I InputDispatcher: Delivering touch to (22536): action: 0x0, f=0x0, d=0, 'd8c938f', t=1 
04-30 22:10:56.834  1000  1131  1817 D PowerManagerService: UserActivityStateListenerState: 1

04-30 22:10:57.483  1000  1131  7181 D SGM:GameManager: identifyGamePackage. com.defold.extension.gpgs, mCurrentUserId: 0, callerUserId: 0, callingMethodInfo: com.android.server.ssrm.SortingMachine.isGame(SortingMachine.java:162)
04-30 22:10:57.483  1000  1131  7181 D SGM:PkgDataHelper: getGamePkgData(). com.defold.extension.gpgs

04-30 22:11:00.422  1000  1131  1450 D MARsPolicyManager: onPackageResumedFG pkgName = com.defold.extension.gpgs, userId = 0
pkgName: com.defold.extension.gpgs, userId: 0

**Comment by britzl** [comment]
I'm not able to reproduce this. I can successfully login from the example project.

![Screenshot_20240611-233440](https://github.com/defold/extension-gpgs/assets/1300688/54c690ed-0bb3-4fc0-b23f-eafda43364f1)

**Comment by dkyles77788** [comment]
Hello there~!
Thanks for checking.

Ok....where should I download the test / example from?
I learned that it needs to be downloaded from play store.
I still get the logged in false message...image attached.

-Derrick

**Comment by dkyles77788** [comment]
Hello again,
I got my code to work.
I had the Game Server for authentication on Google in draft mode the whole
time. I think once I published that it went through. Downloaded example
still does not work for me though.
Could possibly be due to the fact it now has to be downloaded from Google
Play Store?
For me, it only works if I download / install from an upload on
google...adding to phone directly after export does not work.

[image: image.png]

**Comment by britzl** [comment]
Strange, I was testing with the example included with the extension. I tested both with a signed and unsigned build. It could be that my Google user is added as a tester or something like that. It is good that you got it working with your own app!

**Comment by dkyles77788** [comment]
Once I release game, I will put together some sort of walk-through as
Google has changed things around recently after they announced the 14 day
test trial for users.
